### ISSUE TITLE
Climsmart selection too high

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/WSMPA2#101]
For smaller features, the selection of the core can be greater than the target. Then when the non-core area target is calculated, the target is negative. For the moment, this is set to zero automatically. 

As an additional change, we should change the selection of the core to be 100 % only when it doesn't exceed the target.

Part of this problem will be fixed when we address #62 and start interpolating, but we should at least add a check to ensure the targets are not too high. This is not a huge issue as it is only a problem for small features, but it would be good to get it right.

**Comment by jaseeverett** [comment]
This also seems to be a problem when the targets are 100%. Some features end up with rounding error targets greater than 1 (+1e-16). Investigate if this is a rounding error, or a calculation problem. In particular it is happening with small features (Marine IBAs).

**Comment by tinbuenafe** [comment]
Should be fixed in #163. Please check if it works on your end @jaseeverett
