### ISSUE TITLE
Climate refugia module - introductory text

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#127]
Kernel density estimates for the climate-resilience metric. The metric represents climate refugia and comprises two components, both based on projected temperature in 2100 from a suite of Earth System Models under a high emission scenario: 1. Exposure to climate change (amount of warming); 2. Climate velocity (the pace of isotherm movement). These two components are combined into a single climate-resilience metric so that higher values represent areas likely to warm less and where biodiversity is more likely to be retained. The prioritization preferentially places protected areas where there are higher values of the climate-resilience metric, whilst still meeting the biodiversity targets and minimising overlap with rational use areas. The colored polygon represents the climate-resilience metric in planning units selected for protection; the gray polygon represents the climate-resilience metric in areas not selected for protection.

**Comment by tinbuenafe** [comment]
Done. See #142. Along with this, I also added/edited the text for the climate-resilient stuff in the Welcome page and in the Help/Technical Info page following the document sent around through email.
