### ISSUE TITLE
Climate resilience metric - recalculate so higher is better

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#128]
We currently have lower values for the climate resilience metric (and previously the climate-smart metric) as better. This will confuse people. In a previous issue raised, I changed the text on the Climate refugia tab to say higher values of climate resilence are better. Can we recast the metric slightly so this is the case? 100 - CurrentValue would work...

**Comment by tinbuenafe** [comment]
Sent the new climate layers to Jase now.
