### ISSUE TITLE
Update Welcome page text

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/WSMPA2#131]
GG to provide updated welcome page text

**Comment by ric325** [comment]
Make sure this is included:

My suggestion is to make Climate resilience #5 in our list and move current #5 and #6 down one.

Suggested text:
5. Climate refugia. Climate-resilient spatial planning tries to ensure MPAs are robust to impacts of climate change. We calculate a climate-resilience metric that represents climate refugia, whereby higher values represent areas likely to warm less and where biodiversity is more likely to be retained. Thus, the prioritization preferentially places protected areas where there are higher values of the climate-resilience metric, whilst still meeting the biodiversity objectives and minimising overlap with rational use areas. See Help/Technical Information for more details.

**Comment by jaseeverett** [comment]
Updated
