### ISSUE TITLE
Remove climate-smart FAQs

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#137]
FAQs should just be for issues pertaining to running the App. We have captured the climate-smart FAQs in Help/Technical Information

**Comment by tinbuenafe** [comment]
Done. See #142. I kept one question though (see below). Sandra and I thought that it might be a common question that could be raised by the stakeholders.

**_In the comparison module, when I set input 1 as climate-resilient, why does input 2 automatically mirror all the selected features?_**

Comparing a climate-resilient spatial plan with a non-climate-resilient spatial plan with different features and targets will most likely not lead to a useful comparison. Therefore, we suggest comparing a climate-resilient and non-climate-resilient spatial plans with the same features and targets. Further, we provide the option of creating different climate-resilient spatial plans and comparing these.
