### ISSUE TITLE
In Scenario: For particle tracking, grey out Decay options if Accumulation not selected?

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#138]
3.2.2 Particle Tracking
  Accumulation
Select one only:

  Decay - None
 Decay (090 days)
 Decay (360 days)
 Decay (540 days)

**Comment by jaseeverett** [comment]
Closing this issue. This was not the intention (they could be used independently) but everything will change now there are new particle tracking layers
