### ISSUE TITLE
We need to be able to determine what geomorphic features are Important?

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#140]
Currently, from the Layer Maps dropdown listbox and the Layer Justification tab, I cannot tell which geomorphic features are Important. My understanding is that some are...

**Comment by jaseeverett** [comment]
@ric325 The important features are outlined in the text above the plot

**Comment by jaseeverett** [comment]
I have changed the output text to be HTML so it renders as a numbered list and places more emphasis on the important features.
