### ISSUE TITLE
Acknowledge packages used to create climate layers and to do climate priority area approach

### ISSUE THREAD

**Issue by tinbuenafe** [MathMarEcol/WSMPA2#148]

**Comment by tinbuenafe** [comment]
@jaseeverett I noticed that you didn't acknowledge `sf` in the app. So, I'm wondering whether I should acknowledge the packages that I used to create the climate layers/implement the climate priority area approach.

More specifically, the following (omitted those that have already been acknowledged):

- sf
- stats
- raster
- VoCC
- terra

**Comment by jaseeverett** [comment]
@jaseeverett also needs to add shinyalert and shinydisconnect by [Dean Attali](https://github.com/daattali/)

**Comment by tinbuenafe** [comment]
Have added VoCC and terra. sf was already there.

**Comment by tinbuenafe** [comment]
Added shinyalert and shinydisconnect. See #177
