### ISSUE TITLE
Text suggestions by Ant

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#157]
I raised these as issues and they were closed I think but I can't see the text reflected in my version of the App at https://mathmarecol.shinyapps.io/WSMPA2/.? Not sure if I'm missing something...
[ClimateResilienceTextv2.docx](https://github.com/MathMarEcol/WSMPA2/files/9561694/ClimateResilienceTextv2.docx)
[ShinyApp_HelpTechnicalInformationv2.docx](https://github.com/MathMarEcol/WSMPA2/files/9561696/ShinyApp_HelpTechnicalInformationv2.docx)

**Comment by jaseeverett** [comment]
The online app doesn't represent the state of the GitHub repository or the Github version of the app. All these changes were implemented by @tinbuenafe. The online app will be updated when it is stable again.
