### ISSUE TITLE
One sentence in Help/Technical Info is out of place

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#164]
"Thus, the prioritization preferentially places protected areas where there are higher values of the climate-resilience metric, whilst still meeting the biodiversity objectives and minimising overlap with rational use areas." 

This sentence should be at the end of the previous paragraph. i.e. after: "This approach is applied to each Important and Representative features." I think it goes best there. Sorry, my fault with what I sent you...

**Comment by tinbuenafe** [comment]
Done. See #163
