### ISSUE TITLE
Welcome page - 5. Select climate refugia

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#165]
Update first and second sentence of #5. Select climate refuge. My suggestion from before didn't get updated.

"5. Select climate refugia. This option allows you to make the spatial plan climate resilient - i.e. the algorithm will try to ensure suggested MPAs are robust to impacts of climate change to 2100. We achieve this by calculating a climate-resilience..."

thx
ant

**Comment by tinbuenafe** [comment]
Done. See #163
