### ISSUE TITLE
Adding Chawarski et al. reference Benny suggested to include...

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#166]
I think this reference goes best in: 

Under Help/Technical Information/Climate-resilient spatial planning

Change: "This is because temperature projections from climate models are the most reliable (Raaisaanen, 2007) and temperature-derived metrics have been found to be the some of the most important drivers of biodiversity change (e.g., Burrows et al., 2014)."

To: "This is because temperature is usually the main driver of biodiversity patterns (Chawarski et al. 2022), projections of temperature from Earth system models are more reliable than for other variables (Raaisaanen, 2007), and temperature-derived metrics are strongly related to changes in biodiversity under climate change (Burrows et al., 2014; Molinos et al. 2016)."

EXTRA REFS
Chawarski, Julek, Thor A. Klevjer, David Coté, and Maxime Geoffroy. “Evidence of Temperature Control on Mesopelagic Fish and Zooplankton Communities at High Latitudes.” Frontiers in Marine Science 9 (2022). https://www.frontiersin.org/articles/10.3389/fmars.2022.917985.

Molinos G, Halpern BS, Schoeman DS, Brown CJ, Kiessling W, Moore PJ, Pandolfi JM, Poloczanska ES, Richardson AJ, Burrows MT (2016) Climate velocity and the future global redistribution of marine biodiversity. Nature Climate Change 6: 83-90

**Comment by tinbuenafe** [comment]
Done. See #163
