### ISSUE TITLE
Change "Candidate scenario" to "Example scenario"

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#168]
In the Scenario tab at the top where the "Example Scenarios" are briefly described, I think the "candidate scenarios" should be changed to "example scenarios":

"Example scenarios have been compiled. To automatically select the inputs for each **candidate scenario** click one of the four buttons below and then click 'Run Analysis'. Further information about the **candidate scenarios** can be found in the Help tab.

**Comment by tinbuenafe** [comment]
Done. Did this for the solution and compare module. See #163
