### ISSUE TITLE
Remove the first FAQ and place the idea in the Help/Technical Info

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#170]
This is because the first FAQ is on the theory of spatial planning, but we have decided that the FAQs should be related to actually running the app.

So my suggestions are:
1. Change the FAQ heading from "General" to "App"
2. Remove the first FAQ
3. Include its message in the Help/Technical Info. Include the idea by modifying first 2 sentences:

There are many different types of spatial planning problems that can be formulated, but here we use the minimum set objective (Rodrigues et al., 2000). This is the most common spatial planning problem, whereby we identify areas of higher conservation priority (i.e., areas with unique or multiple species) whilst minimizing the cost to people (Micheli et al., 2013).

**Comment by tinbuenafe** [comment]
Done. See #177
