### ISSUE TITLE
installation fail - bug

### ISSUE THREAD

**Issue by benjamin-merkel** [MathMarEcol/WSMPA2#185]
install_github("MathMarEcol/WSMPA2")
Downloading GitHub repo MathMarEcol/WSMPA2@HEAD
Error: Failed to install 'WSMPA2' from GitHub:
  Missing commas separating Remotes: 'dirkschumacher/rcbc
    prioritizr/prioritizr'

**Comment by jaseeverett** [comment]
Fixed by PR from devel
