### ISSUE TITLE
north-south stribes at none rational use forcing

### ISSUE THREAD

**Issue by benjamin-merkel** [MathMarEcol/WSMPA2#192]
I noticed that we still get lines in a north-south direction if no forcing/cost/rational use is applied. This is mainly to make you aware of it. 

![WSMPA2_Solution_20220916085116](https://user-images.githubusercontent.com/11088303/190598156-55375c8f-7ea6-46b3-930a-db9a19519c37.png)

**Comment by jaseeverett** [comment]
Yes this is known behaviour. Without a cost layer there is no way for prioritizr to choose between cells that have the same combination of features.

**Comment by tinbuenafe** [comment]
Response from Jeffrey Hanson about this:

> "... When we take the planning unit data use that to build a mathematical problem for optimization, the order of the planning units in the problem follows the order of the planning units in the data. And it seems that the algorithms that Gurobi uses are likely to assign similar solution values to variables that are "next" to each other in the problem (i.e., when the problem is under-specified such that there is a huge number of optimal solutions). It's not necessarily driven by Gurobi "knowing" the spatial location of each planning unit and using that explicitly in the optimization per se, it's more like a default behavior. ..."
