### ISSUE TITLE
Remove Selection Frequency tab???

### ISSUE THREAD

**Issue by ric325** [MathMarEcol/WSMPA2#66]
I find this is problematic. Sometimes it runs very quickly, other times it takes ages for the same thing. Sometimes the reload button comes up. On my laptop it is too intermittent to be in the App??? Happy to discuss and find out others' experiences.

**Comment by jaseeverett** [comment]
@ric325 Please report back if this is still problematic, or should we keep it for the moment?

**Comment by ric325** [comment]
It is running for me now. But when I run with all layers it gives me a frequency of 4, which is fine. When I choose other targets for Important layers then it would sometimes give me a frequency of only 1 or 2, which is not useful? Not sure why? It should have the same frequency all the time I think to be meaningful... @ Tin probably needs to check...

**Comment by ric325** [comment]
I find when I run Scenario for Example 1 and Example 3 then the Selection Frequency doesn't work?

**Comment by jaseeverett** [comment]
@ric325 and I have decided to remove this for the moment. It is problematic due to CPU use, complexity, and errors we can't  fix at the moment.
