### ISSUE TITLE
Add text to some features

### ISSUE THREAD

**Issue by tinbuenafe** [MathMarEcol/WSMPA2#90]
We're still missing descriptive text on some features (see Layer Information Module)

Change text and/or title for:

- [x] Southern Ocean Biogeochemical Divide
- [x] All particle tracking layers
- [x] Benthic ecoregions (has text, but there's a placeholder for checking the reference cited)
- [x] All rational uses

**Comment by tinbuenafe** [comment]
Making this a little more detailed now. Just some observations in the layer information @jaseeverett 

- Should it really be "Habitat Suitability of"... 
1. Areas of Ecological Significance
2. Important Bird Areas
3. Areas of Earlier Ice Retreat
4. Coastal Polynya
5. Spring Marginal Ice Zone

**Comment by jaseeverett** [comment]
Have changed all these and update the text.
